global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.IdentityModel.Tokens;
global using movie_app_graduation_api.Helper;
global using movie_app_graduation_api.Models;
global using movie_app_graduation_api.Models.Data;
global using movie_app_graduation_api.Services.Authenticate;
global using System.ComponentModel.DataAnnotations;
